import { Lesson, LanguageCode, Slide } from './deck/types';
import manifestFr from './data/audio/manifest.fr.json';
import manifestEs from './data/audio/manifest.es.json';
import manifestIt from './data/audio/manifest.it.json';
import manifestPt from './data/audio/manifest.pt.json';
import manifestDe from './data/audio/manifest.de.json';
import imageManifest from './data/images/manifest.json';

// Generated by `npm run audio` (ElevenLabs): per-segment mp3 + REAL duration.
type AudioManifest = { segments: Record<string, { audioSrc?: string; durationInSeconds?: number }> };
const MANIFESTS: Record<LanguageCode, AudioManifest> = {
  fr: manifestFr as AudioManifest,
  es: manifestEs as AudioManifest,
  it: manifestIt as AudioManifest,
  pt: manifestPt as AudioManifest,
  de: manifestDe as AudioManifest,
};

// Overlay generated narration timing/audio onto the authored slides. Until the
// ElevenLabs step runs, manifests are empty and the placeholder durations stand.
const applyAudio = (slides: Slide[], language: LanguageCode): Slide[] => {
  const segs = MANIFESTS[language]?.segments ?? {};
  return slides.map((s) => {
    const a = segs[s.id];
    if (!a) return s;
    return {
      ...s,
      durationInSeconds: a.durationInSeconds ?? s.durationInSeconds,
      audioSrc: a.audioSrc ?? s.audioSrc,
    };
  });
};

// Generated by `npm run images` (Firefly): language-agnostic per-segment images
// (title illustration + vocab word image), reused across all five channels.
type ImageManifest = { segments: Record<string, { imageSrc?: string; imageSrcs?: string[] }> };
const applyImages = (slides: Slide[]): Slide[] => {
  const segs = (imageManifest as ImageManifest).segments ?? {};
  return slides.map((s) => {
    const im = segs[s.id];
    if (!im?.imageSrc) return s;
    if (s.type === 'title') return { ...s, imageSrc: im.imageSrc };
    if (s.type === 'vocab') return { ...s, imageSrc: im.imageSrc, imageSrcs: im.imageSrcs };
    return s;
  });
};

// Sample "Everyday verbs" lesson, translated per language, used as the default
// preview content for each channel's template. Real lessons come from the
// workbook → pipeline export later; this proves per-language theming + copy.
//
// Durations are placeholders here (a few seconds each). Once ElevenLabs
// narration is wired, each slide's durationInSeconds will be set from the
// ACTUAL returned audio length so visuals stay locked to the voice.

type Content = {
  chrome: { lessonA: string; lessonB: string; progressLabel: string; wordUnit: string };
  repeat: string;
  title: { kicker: string; titleLines: [string, string] };
  vocab: { word: string; phonetic: string; pos: string };
  buildup: { eyebrow: string; steps: { base: string; add?: string }[] };
  yourturn: { cue: string; prompt: string; sub: string };
  model: { eyebrow: string; highlight: string; rest: string; compareNote: string };
  score: {
    headline: string;
    nowSayLead: string;
    nowSaySentence: string;
    wordsTodayLabel: string;
    levelLabel: string;
    sentencesLabel: string;
  };
};

const CONTENT: Record<LanguageCode, Content> = {
  fr: {
    chrome: { lessonA: 'Leçon 4', lessonB: 'Les verbes', progressLabel: 'Progression', wordUnit: 'mots' },
    repeat: 'Répète',
    title: { kicker: 'Leçon 4', titleLines: ['Les verbes', 'du quotidien'] },
    vocab: { word: 'travailler', phonetic: 'tra-va-YAY', pos: 'verbe' },
    buildup: {
      eyebrow: 'On construit la phrase',
      steps: [
        { base: 'Je travaille.' },
        { base: 'Je travaille', add: 'au Canada.' },
        { base: 'Je travaille au Canada', add: 'avec mon équipe.' },
      ],
    },
    yourturn: { cue: 'À toi !', prompt: 'Écris ta propre phrase.', sub: 'Utilise un autre sujet — parle de ta vie.' },
    model: { eyebrow: 'Exemple de réponse', highlight: 'Nous travaillons', rest: ' à Toronto.', compareNote: 'Compare avec ta phrase.' },
    score: {
      headline: 'Bravo !',
      nowSayLead: 'Tu peux maintenant dire :',
      nowSaySentence: 'Je travaille au Canada.',
      wordsTodayLabel: 'mots aujourd’hui',
      levelLabel: 'niveau',
      sentencesLabel: 'phrases écrites',
    },
  },
  es: {
    chrome: { lessonA: 'Lección 4', lessonB: 'Los verbos', progressLabel: 'Progreso', wordUnit: 'palabras' },
    repeat: 'Repite',
    title: { kicker: 'Lección 4', titleLines: ['Los verbos', 'del día a día'] },
    vocab: { word: 'trabajar', phonetic: 'trah-bah-HAR', pos: 'verbo' },
    buildup: {
      eyebrow: 'Construimos la frase',
      steps: [
        { base: 'Yo trabajo.' },
        { base: 'Yo trabajo', add: 'en Canadá.' },
        { base: 'Yo trabajo en Canadá', add: 'con mi equipo.' },
      ],
    },
    yourturn: { cue: '¡Tu turno!', prompt: 'Escribe tu propia frase.', sub: 'Usa otro sujeto — habla de tu vida.' },
    model: { eyebrow: 'Ejemplo de respuesta', highlight: 'Nosotros trabajamos', rest: ' en Toronto.', compareNote: 'Compara con tu frase.' },
    score: {
      headline: '¡Bravo!',
      nowSayLead: 'Ahora puedes decir:',
      nowSaySentence: 'Yo trabajo en Canadá.',
      wordsTodayLabel: 'palabras hoy',
      levelLabel: 'nivel',
      sentencesLabel: 'frases escritas',
    },
  },
  it: {
    chrome: { lessonA: 'Lezione 4', lessonB: 'I verbi', progressLabel: 'Avanzamento', wordUnit: 'parole' },
    repeat: 'Ripeti',
    title: { kicker: 'Lezione 4', titleLines: ['I verbi', 'di ogni giorno'] },
    vocab: { word: 'lavorare', phonetic: 'lah-vo-RAH-reh', pos: 'verbo' },
    buildup: {
      eyebrow: 'Costruiamo la frase',
      steps: [
        { base: 'Io lavoro.' },
        { base: 'Io lavoro', add: 'in Canada.' },
        { base: 'Io lavoro in Canada', add: 'con la mia squadra.' },
      ],
    },
    yourturn: { cue: 'Tocca a te!', prompt: 'Scrivi la tua frase.', sub: 'Usa un altro soggetto — parla della tua vita.' },
    model: { eyebrow: 'Esempio di risposta', highlight: 'Noi lavoriamo', rest: ' a Toronto.', compareNote: 'Confronta con la tua frase.' },
    score: {
      headline: 'Bravo!',
      nowSayLead: 'Ora sai dire:',
      nowSaySentence: 'Io lavoro in Canada.',
      wordsTodayLabel: 'parole oggi',
      levelLabel: 'livello',
      sentencesLabel: 'frasi scritte',
    },
  },
  pt: {
    chrome: { lessonA: 'Lição 4', lessonB: 'Os verbos', progressLabel: 'Progresso', wordUnit: 'palavras' },
    repeat: 'Repete',
    title: { kicker: 'Lição 4', titleLines: ['Os verbos', 'do dia a dia'] },
    vocab: { word: 'trabalhar', phonetic: 'trah-bah-LYAR', pos: 'verbo' },
    buildup: {
      eyebrow: 'Vamos construir a frase',
      steps: [
        { base: 'Eu trabalho.' },
        { base: 'Eu trabalho', add: 'no Canadá.' },
        { base: 'Eu trabalho no Canadá', add: 'com a minha equipa.' },
      ],
    },
    yourturn: { cue: 'É a tua vez!', prompt: 'Escreve a tua própria frase.', sub: 'Usa outro sujeito — fala da tua vida.' },
    model: { eyebrow: 'Exemplo de resposta', highlight: 'Nós trabalhamos', rest: ' em Toronto.', compareNote: 'Compara com a tua frase.' },
    score: {
      headline: 'Parabéns!',
      nowSayLead: 'Agora consegues dizer:',
      nowSaySentence: 'Eu trabalho no Canadá.',
      wordsTodayLabel: 'palavras hoje',
      levelLabel: 'nível',
      sentencesLabel: 'frases escritas',
    },
  },
  de: {
    chrome: { lessonA: 'Lektion 4', lessonB: 'Die Verben', progressLabel: 'Fortschritt', wordUnit: 'Wörter' },
    repeat: 'Wiederhole',
    title: { kicker: 'Lektion 4', titleLines: ['Verben für', 'den Alltag'] },
    vocab: { word: 'arbeiten', phonetic: 'AR-bai-ten', pos: 'Verb' },
    buildup: {
      eyebrow: 'Wir bauen den Satz',
      steps: [
        { base: 'Ich arbeite.' },
        { base: 'Ich arbeite', add: 'in Kanada.' },
        { base: 'Ich arbeite in Kanada', add: 'mit meinem Team.' },
      ],
    },
    yourturn: { cue: 'Du bist dran!', prompt: 'Schreib deinen eigenen Satz.', sub: 'Nimm ein anderes Subjekt — sprich über dein Leben.' },
    model: { eyebrow: 'Beispielantwort', highlight: 'Wir arbeiten', rest: ' in Toronto.', compareNote: 'Vergleiche mit deinem Satz.' },
    score: {
      headline: 'Super!',
      nowSayLead: 'Du kannst jetzt sagen:',
      nowSaySentence: 'Ich arbeite in Kanada.',
      wordsTodayLabel: 'Wörter heute',
      levelLabel: 'Niveau',
      sentencesLabel: 'Sätze geschrieben',
    },
  },
};

export const getSampleLesson = (language: LanguageCode): Lesson => {
  const c = CONTENT[language];
  return {
    title: `${c.chrome.lessonA} — ${c.chrome.lessonB}`,
    language,
    ui: { repeat: c.repeat },
    chrome: {
      lessonA: c.chrome.lessonA,
      lessonB: c.chrome.lessonB,
      level: 'A1',
      progressLabel: c.chrome.progressLabel,
      wordUnit: c.chrome.wordUnit,
      wordsFrom: 142,
      wordsTo: 150,
      wordsTotal: 300,
    },
    slides: applyImages(applyAudio([
      {
        id: 'title',
        type: 'title',
        durationInSeconds: 5,
        kicker: c.title.kicker,
        titleLines: c.title.titleLines,
        subtitle: 'Everyday verbs',
      },
      {
        id: 'vocab-1',
        type: 'vocab',
        durationInSeconds: 7,
        word: c.vocab.word,
        translation: 'to work',
        phonetic: c.vocab.phonetic,
        pos: c.vocab.pos,
      },
      {
        id: 'buildup-1',
        type: 'buildup',
        durationInSeconds: 9,
        eyebrow: c.buildup.eyebrow,
        steps: c.buildup.steps,
        translation: 'I work in Canada with my team.',
      },
      {
        id: 'yourturn-1',
        type: 'yourturn',
        durationInSeconds: 10,
        cue: c.yourturn.cue,
        prompt: c.yourturn.prompt,
        sub: c.yourturn.sub,
        seconds: 10,
      },
      {
        id: 'model-1',
        type: 'model',
        durationInSeconds: 5,
        eyebrow: c.model.eyebrow,
        highlight: c.model.highlight,
        rest: c.model.rest,
        compareNote: c.model.compareNote,
        translationEn: 'We work in Toronto.',
      },
      {
        id: 'score',
        type: 'score',
        durationInSeconds: 6,
        headline: c.score.headline,
        nowSayLead: c.score.nowSayLead,
        nowSaySentence: c.score.nowSaySentence,
        stats: {
          wordsToday: '+8',
          wordsTodayLabel: c.score.wordsTodayLabel,
          levelValue: 'A1 · 142/300',
          levelLabel: c.score.levelLabel,
          levelPct: 47,
          sentences: '6',
          sentencesLabel: c.score.sentencesLabel,
        },
      },
    ], language)),
    overlays: [],
  };
};
